image: ${GV_REGISTRY_ADDRESS}/${GV_BUILD_IMAGE_NAME}

cache:
  key: ${CI_PROJECT_PATH_SLUG}
  paths:
    - node_modules

stages:
  - '.pre'
  - pre
  - qa
  - build
  - test
  - tag
  - publish
  - scan
  - delete
  - release
  - promote
  - promote_product
  - deploy
  - '.post'

variables:
  TEAM: 'onecx'
  DOMAIN: 'onecx-platform'
  BUSINESS_DATA_DOMAIN: 'giga-installation-order'
  CONV_COMMIT_SEMVER: 'true'
  PL_COMMIT_BASED_FINAL_TAG_CHANGELOG: 'true'
  NPM_SONAR: 'true'
  NPM_BUILDER_VERSION: 'node-v18'

include:
  - project: '${GV_PIPELINE_INCLUDE_PREFIX}infr/pipelines/service/ci/common'
    ref: v2
    file: '/public/js/npm/gitflow.yml'
  - project: '${GV_PIPELINE_INCLUDE_PREFIX}infr/pipelines/service/ci/common'
    ref: v2
    file: '/public/conf/definition.yml'
  - project: '${GV_PIPELINE_INCLUDE_PREFIX}infr/pipelines/service/ci/common'
    ref: v2
    file: '/public/conf/gitflow.yml'
  - project: '${GV_PIPELINE_INCLUDE_PREFIX}infr/deployment/pipeline-logic/conv-commit-semver-rc-tag'
    ref: v2
    file: 'tag-conv_commit_semver.yaml'
  - project: '${GV_PIPELINE_INCLUDE_PREFIX}infr/deployment/pipeline-logic/conv-commit-semver-final-tag'
    ref: v1
    file: 'tag-conv_commit_semver.yaml'
  - project: ${GV_PIPELINE_INCLUDE_PREFIX}infr/deployment/pipeline-logic/promotion
    ref: v2
    file: promote-gitflow.yaml  

npm:build:
  stage: build
  script:
    - npm i @openapitools/openapi-generator-cli
    - npm run apigen
    - npm install
    - npm run build

# disable team promotion as there is not a onecx team
promote:team-conv_commit_semver:
  rules:
    - when: never
    